import { ThemeProvider } from '@/components/theme-provider';
import Header from '@/components/top';
import { cn } from '@/lib/utils';
import type { Metadata, Viewport } from 'next';
import LocalFont from 'next/font/local';

import './globals.css';

const maple = LocalFont({
  src: '../public/MapleMono-Regular.woff2',
  variable: '--font-maple',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'hsl(0 0% 100%)' },
    { media: '(prefers-color-scheme: dark)', color: 'hsl(222.2 84% 4.9%)' },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'flex min-h-dvh flex-col font-maple antialiased',
          maple.variable
        )}
      >
        <ThemeProvider>
          <Header />
          <div className="container flex h-full max-w-5xl flex-grow py-6">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
